### ISSUE TITLE
[Inquiry] Performance compared to native Android

### ISSUE THREAD

**Issue by ankandrew** [KoheiKanagu/ncnn_yolox_flutter#24]
Hi thanks for the work.

How much more time does it take doing the inference with flutter in android (preprocessing and analyzing frames) compared when running YOLOX natively on android?

**Comment by KoheiKanagu** [comment]
@ankandrew Hi

Sorry, I have not benchmarked it.
I don't know exactly, but I don't think there is a big difference.

Because the heavy preprocessing, e.g. YUV420SP to RGB conversion, is executed native.
https://github.com/KoheiKanagu/ncnn_yolox_flutter/blob/74adaf7ee26f187cb2dc4fa3eacbd7d68e8b290a/lib/ncnn_yolox.dart#L306-L311

dart:ffi may affect performance, but since it is only a memory copy process, I think the impact will be small.
If the images are very large, I think it will affect performance.
https://github.com/KoheiKanagu/ncnn_yolox_flutter/blob/74adaf7ee26f187cb2dc4fa3eacbd7d68e8b290a/lib/ncnn_yolox.dart#L299-L317

When streaming images, the overhead of the Camera plugin will also affect performance, but I don't know to what extent.
https://github.com/KoheiKanagu/ncnn_yolox_flutter/blob/74adaf7ee26f187cb2dc4fa3eacbd7d68e8b290a/example/lib/widgets/image_stream_floating_action_button_widget.dart#L85-L114

**Comment by ankandrew** [comment]
Awesome, thanks. If I do a comparison, I'll post benchmark here :)

**Comment by kikirizki** [comment]
Hi @ankandrew any update about benchmark result?
